// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/call.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/open.tsx";
import * as $$0 from "./islands/Button.tsx";
import * as $$1 from "./islands/CallAppBtn.tsx";
import * as $$2 from "./islands/CallAppUp.tsx";
import * as $$3 from "./islands/CopyBtn.tsx";
import * as $$4 from "./islands/DownloadBtn.tsx";
import * as $$5 from "./islands/Input.tsx";
import * as $$6 from "./islands/Qrcode.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/call.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/open.tsx": $3,
  },
  islands: {
    "./islands/Button.tsx": $$0,
    "./islands/CallAppBtn.tsx": $$1,
    "./islands/CallAppUp.tsx": $$2,
    "./islands/CopyBtn.tsx": $$3,
    "./islands/DownloadBtn.tsx": $$4,
    "./islands/Input.tsx": $$5,
    "./islands/Qrcode.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
